init project and init tracing API
SkyAPM/SkyAPM-nodejs pull request #1
Opened 2018-04-06 00:42 UTC by ascrutae

2018-04-15 03:42 UTC, ascrutae commented
@wu-sheng I had finished the trace api, Could you help me to check this PR if you are free.

2018-04-21 15:24 UTC, wu-sheng commented on README.md
> +The Node serverB instrument SDK for Apache SkyWalking
Please make sure the README is official and right.

2018-04-21 15:25 UTC, wu-sheng commented on .gitignore
> +example/
Why does git ignore include the `example` folder?

2018-04-23 06:59 UTC, wu-sheng requested changes
I have some concerns in comments. Besides that, I also want to know, what happens if TraceContext works with some NoopContext? Because from your codes, the context created with span, and application id and instance id could be set in any time.

2018-04-23 06:59 UTC, wu-sheng commented on lib/plugins/supported/http.js
> +                if (req.headers.hasOwnProperty("sw3")) {
The ContextCarrier API is not coded in right way.

2018-04-23 06:59 UTC, wu-sheng commented on lib/instrumentation/index.js
> +        contextManager.active(runningTraceContext);
Is there any possibility the runningTraceContext or previousTraceContext `unidentified`?

2018-04-23 06:59 UTC, wu-sheng commented on lib/instrumentation/index.js
> +            runningTraceContext.log(err);
Why could the context log and tag error?

2018-04-23 06:59 UTC, wu-sheng commented on lib/trace/context-manager.js
> +    if (!AgentConfig.getApplicationId()) {
When  application instance id is NULL, span shouldn't be created.

2018-04-23 06:59 UTC, wu-sheng commented on lib/trace/context-manager.js
> +    if (!AgentConfig.getApplicationId()) {
When  application instance id is NULL, span shouldn't be created.

2018-04-23 06:59 UTC, wu-sheng commented on lib/trace/context-manager.js
> +    if (!AgentConfig.getApplicationId()) {
And `#createSpan` has already included this check, where do you prefer to do this?

2018-04-23 14:38 UTC, wu-sheng commented on lib/plugins/supported/http.js
> +                contextCarrier.fetchTracingContext(function (key) {
Why named `#contextCarrier.fetchTracingContext`? In our module, this should be named as `#extract`

2018-04-25 13:20 UTC, wu-sheng approved these changes

2018-04-25 13:20 UTC, merged